services:
  - type: web
    name: testAppStrava
    env: python
    plan: free
    buildCommand: 
    - pip install --upgrade pip
    - pip install numpy==1.26.4
    - pip install -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
